In [1]:
#importing the tensorflow library
import tensorflow as tf
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [35]:
#Checking if it support eager execution
tf.executing_eagerly()

True

In [36]:
tf.__version__

'2.1.0'

### Tensorflow Operations

#### Making tensors with tf.constant and tf.Variable
Difference is a constant tensor cannot change while a variable tensor can change

In [19]:
#creating a constant tensor
a = tf.constant([[2,3],
                 [3,4]], name='constant_a')
b = tf.constant([[3,4],
                 [4,5]], name = 'constant_b')

tf.Tensor(
[[2 3]
 [3 4]], shape=(2, 2), dtype=int32) tf.Tensor(
[[3 4]
 [4 5]], shape=(2, 2), dtype=int32)


In [18]:
#Creating a variable tensor c and d
c = tf.Variable([[4,5],
                 [5,6]])
d = tf.Variable([[6,7],
                 [7,8]])

In [21]:
#to check the data shape of each
a.shape

TensorShape([2, 2])

In [23]:
#to concatenate two tensors together
e = tf.concat(values=[a,b], axis =0)
print(e.numpy())

[[2 3]
 [3 4]
 [3 4]
 [4 5]]


In [29]:
#to concatenate two tensors together
f = tf.concat(values=[a,b], axis =1)
print(f.numpy())

[[2 3 3 4]
 [3 4 4 5]]


In [30]:
#to reshape data
g = tf.reshape(e, [1,8])
print(g)

tf.Tensor([[2 3 3 4 3 4 4 5]], shape=(1, 8), dtype=int32)


In [32]:
# to find the transpose of a matrix
tf.transpose(e)
print(e)

tf.Tensor(
[[2 3 3 4]
 [3 4 4 5]], shape=(2, 4), dtype=int32)


In [34]:
#casting a tensor to other data types
h = tf.cast(f, float)
print(h)

tf.Tensor(
[[2. 3. 3. 4.]
 [3. 4. 4. 5.]], shape=(2, 4), dtype=float32)


### Data Structure

In [4]:
#Defining multidimentional arrays using tf

scaler = tf.constant(2)
vector = tf.constant([1,2,3,4,5])
matrix = tf.constant([[1,3,4],
                    [4,5,6],
                     [6,7,8]])
tensor = tf.constant([[[1,2,3], [2,3,4],[4,5,6]],
                     [[1,2,3], [2,3,4],[5,6,7]],
                     [[1,2,3], [2,3,4],[4,5,6]]])

In [5]:
print ("Scalar (1 entry):\n %s \n" % scaler)
print ("Vector (3 entries) :\n %s \n" % vector)
print ("Matrix (3x3 entries):\n %s \n" % matrix)
print ("Tensor (3x3x3 entries) :\n %s \n" % tensor)

Scalar (1 entry):
 tf.Tensor(2, shape=(), dtype=int32) 

Vector (3 entries) :
 tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32) 

Matrix (3x3 entries):
 tf.Tensor(
[[1 3 4]
 [4 5 6]
 [6 7 8]], shape=(3, 3), dtype=int32) 

Tensor (3x3x3 entries) :
 tf.Tensor(
[[[1 2 3]
  [2 3 4]
  [4 5 6]]

 [[1 2 3]
  [2 3 4]
  [5 6 7]]

 [[1 2 3]
  [2 3 4]
  [4 5 6]]], shape=(3, 3, 3), dtype=int32) 



In [6]:
matrix.shape

TensorShape([3, 3])

### Performing basic Algebraic Operations

#### 1.Transpose tensor with tf.transpose

In [44]:
# Perfoming tanspose of e
e_tp = tf.transpose(e)
print ('e.\n{}'.format(e), '\ne_transpose.\n{}'.format(e_tp))

e.
[[2 3 3 4]
 [3 4 4 5]] 
e_transpose.
[[2 3]
 [3 4]
 [3 4]
 [4 5]]


#### 2. Matrix Multiplication with tf.matmul

In [48]:
print('c \n{}'.format(c.numpy()), '\nd \n{}'.format(d.numpy()) )

c 
[[4 5]
 [5 6]] 
d 
[[6 7]
 [7 8]]


In [49]:
tf.matmul(c,d)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[59, 68],
       [72, 83]])>

#### 3.Element-wise multiplication with tf.multiply

In [50]:
print('b \n{}'.format(b.numpy()) )

b 
[[3 4]
 [4 5]]


In [51]:
tf.multiply(b,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 20],
       [20, 25]])>

#### 4. Identity Matrix with tf.eye

In [56]:
Id = tf.eye(3,3)
print(Id)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


#### 5. Finding Determinant of a matrix with tf.linalg.det

In [62]:
# Determinant must be: half, float32, float64, complex64, complex128
det =tf.linalg.det(Id)
print(det.numpy())

1.0


#### 6. Dot Product with tf.tensordot

In [64]:
a = tf.constant([[1,2,3],
                 [2,3,4],
                 [3,4,5]])
b = tf.constant([[4,5,6],
                 [5,6,7],
                 [7,8,9]])
dot = tf.tensordot(a,b,axes =1)
print(dot)

tf.Tensor(
[[35 41 47]
 [51 60 69]
 [67 79 91]], shape=(3, 3), dtype=int32)
